### ISSUE TITLE
String key indentation issues inside Map

### ISSUE THREAD

**Issue by natrys** [wkirschbaum/elixir-ts-mode#7]
Help with debugging this would be appreciated (I am trying to grok tree-sitter on the fly). The issue is, up to this is fine (pipe denotes cursor):

``` elixir
map = %{
  "a" => 1|
}
```

But if I try and add a second element, the moment I complete the second key (string), the item indents:

``` elixir
map = %{
  "a" => 1,
    "b"|
}
```

I have a couple of tangential questions. How do I intuit which indent rule just got triggered? Do you know if Emacs goes through *all* the `treesit-simple-indent-rules` one by one, or stops when first rule is matched? When cursor is at the second example, when I do `(treesit-node-parent (treesit-node-at (point)))`, I get back `string` but the corresponding string indent rule seems quite innocuous `((parent-is "string") parent-bol 0)`.

Second question is, the corresponding indent rule to the matcher `(parent-is "quoted_content")` seems kind of fancy, but in what circumstance does it get triggered? Looking at the grammar `quoted_content` seems like a leaf node to me.

**Comment by natrys** [comment]
Sorry about the stream of consciousness, but I think I found how to debug this. Looking at `treesit-simple-indent` function, I think it short-circuits after first successful rule match, and it even logs the rule if I set `treesit--indent-verbose`. Except in the above example, what I get is: `Matched rule: ((parent-is "map") parent-bol 2)`

It's still confusing to me as to why that rule is getting matched.

**Comment by wkirschbaum** [comment]
@natrys thanks for having a look. There will be a lot of tweaking required for indentation. Logging the issue is helpful, because I will slowly add those to the test cases. 

You can have a look at `M-x treesit-explore-mode` which might help. There are some quirks and some compromises we need to consider. I initially wanted to make it work 100% like the current mix format command, but realised that the performance penalty is pretty significant and also think mix format has somewhat random behaviour ( maybe )... 

I will be more present from tomorrow onward to have a more detailed look at the issues. There is also some work I believe we can do with the tree-sitter grammars to make indentation easier and already logged some issues, but think they require much more consideration.

This package will probably be merged into emacs core in the next month or two,  so at this moment I won't be accepting significant changes from non-emacs contributors to reduce the amount of admin.

**Comment by natrys** [comment]
Yeah, `treesit-explore-mode` was useful. In any case I think I have found the root of the issue, though your confirmation could be great. 

When I trace `treesit-simple-indent` function, I find it's getting called with current node being `string` and its parent being `map_content`. This matches what I see in the tree, so that's great.

However, this still matches the rule `(parent-is "map")` even though "map" is the *grand parent*, while parent is "map_content". The reasons is, parent-is is actually implemented in terms of `string-match-p` as opposed to `string-equal`. So the call boils down to `(string-match-p "map" "map_content")` which accidentally returns true, even though the rule for "map" wasn't meant to validate "map_content".

Why treesit.el is using `string-match-p` instead of `string-equal` eludes me, that would be a question for emacs-devel. Meanwhile, this issue would be solved if you tighten the pattern to prevent accidentally matching another node, e.g. by changing `"map"` to `"^map$"`. In my testing, this solved the issue.

Good to know about plans to merge this in Emacs core. I haven't had the paperwork done yet, though I made some small patches to core before and was told it's fine so long as change is smaller than 15 lines.

**Comment by wkirschbaum** [comment]
Thanks, you got it spot on. I was not aware that the matchers uses regexp, so just convert all of the matchers to be explicit. Does this change fix your issue? https://github.com/wkirschbaum/elixir-ts-mode/commit/8f99ac9af657726f42ffe78c5f31ac4f57832264

**Comment by natrys** [comment]
Yep it did, thanks. The tests are good ideas too.
